
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EXTERN = 11;
  public static final int EGAL = 9;
  public static final int ELSE = 14;
  public static final int IDENT = 2;
  public static final int PLUS = 27;
  public static final int SUP = 8;
  public static final int INT = 12;
  public static final int SEMI = 19;
  public static final int WHILE = 15;
  public static final int MULTI = 28;
  public static final int RETURN = 18;
  public static final int SUPEQUAL = 32;
  public static final int MODULO = 30;
  public static final int IF = 13;
  public static final int SHIFTLEFT = 5;
  public static final int INF = 7;
  public static final int DO = 16;
  public static final int STRING = 33;
  public static final int COMMA = 22;
  public static final int EOF = 0;
  public static final int DIV = 29;
  public static final int SHIFTRIGHT = 6;
  public static final int MINUS = 26;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int PARAR = 25;
  public static final int CURLYR = 21;
  public static final int CONST_INT = 3;
  public static final int CONST_STRING = 4;
  public static final int DIFF = 10;
  public static final int FOR = 17;
  public static final int PARAL = 24;
  public static final int CURLYL = 20;
  public static final int INFEQUAL = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "CONST_INT",
  "CONST_STRING",
  "SHIFTLEFT",
  "SHIFTRIGHT",
  "INF",
  "SUP",
  "EGAL",
  "DIFF",
  "EXTERN",
  "INT",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "RETURN",
  "SEMI",
  "CURLYL",
  "CURLYR",
  "COMMA",
  "ASSIGN",
  "PARAL",
  "PARAR",
  "MINUS",
  "PLUS",
  "MULTI",
  "DIV",
  "MODULO",
  "INFEQUAL",
  "SUPEQUAL",
  "STRING"
  };
}

